Next sample
DHTMLX/angular-diagram-demo pull request #2
Opened 2024-06-24 08:59 UTC by Izobov

2024-06-25 07:34 UTC, Sorokin-Oleg requested changes

2024-06-25 07:34 UTC, Sorokin-Oleg commented on README.md
> +![DHTMLX Diagram with Angular Demo](https://raw.githubusercontent.com/DHTMLX/angular-diagram-demo/master/diagram.png)
@Izobov хм, похоже, что ссылка на изображение битая. Либо такого изображения не существует.

2024-06-25 07:34 UTC, Sorokin-Oleg commented on README.md
> +```
@Izobov можно отобразить, что это раздел инсталяции. Выше пишем о клонировании либо скачивании репозитория, а ниже сразу команды, которые к этим действиям не относятся.

2024-06-25 07:34 UTC, Sorokin-Oleg commented on package.json
> -    "storybook": "start-storybook -p 6006 -s public",
@Izobov этот момент нужно у Татьяны уточнить, будем ли разворачивать на `gh-pages`.

2024-06-25 07:34 UTC, Sorokin-Oleg commented on src/app/diagram/diagram.component.css
> +  position: relative;
@Izobov думаю `releative` тут не нужен

2024-06-25 07:34 UTC, Sorokin-Oleg commented on src/app/diagram/diagram.component.ts
> +  private _diagram: any;
@Izobov у нас есть возможность подтянуть типы редактора, `any` в офф примере как-то не официально выглядит)

2024-06-25 07:34 UTC, Sorokin-Oleg commented on src/app/diagram/diagram.component.ts
> +    let diagram = new DiagramEditor(this.diagramContainer.nativeElement, { type: "default" } as IDefaultEditorConfig);
@Izobov локальная переменная тут не нужна, у нас уже есть приватная переменная класса `this._diagram`

2024-06-25 07:45 UTC, Izobov commented on README.md
> +![DHTMLX Diagram with Angular Demo](https://raw.githubusercontent.com/DHTMLX/angular-diagram-demo/master/diagram.png)
@Sorokin-Oleg  пока нет изображения, но потом будет. Положим diagram.png

2024-07-01 14:34 UTC, Sorokin-Oleg approved these changes

2024-07-02 10:02 UTC, merged